version: "3"

services:
  bot:
   build: .
   image: rss_notifier
   container_name: rss_notifier_bot
   command: python bot.py
   restart: unless-stopped
   volumes:
     - ./src/config.toml:/app/config.toml
